config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
 	has_one_attached :image
 	has_one_attached :video
	belongs_to :user
	has_many :comments, as: :commentable, dependent: :destroy

	enum status: [:published, :draft]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_params, only: [:create]

	def create
		@comment = @post.comments.create(comment_params)
		redirect_to post_path(@post)
	end

	private

	def set_params
		@post = Post.find(params[:post_id])
	end

	def comment_params
		params.require(:comment).permit(:name, :text)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user ? Post.where("status = ? OR user_id = ?", Post.statuses[:published], current_user.id) : Post.where(status: 'published')
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.create(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :content, :status, :creation_date, :published_date, :image, :video)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% if post.comments.present? %>
  <% post.comments.each do |comment| %>
    <div class="card">
      <div class="card-body">
        <h6 class="card-title">
          <strong>Name:</strong>
          <%= comment.name %>
        </h6>
        <div class="card-text">
          <strong>Comment:</strong>
          <%= comment.text %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="row">
    <div class="card border-0">
      <div class="card-body text-center">
        <h6 class="card-title text-muted">No comments</h6>
      </div>
    </div>
  </div>  
<% end %>  

app/views/comments/_form.html.erb
<div class="row">
  <%= form_with model: [ post, post.comments.build ] do |form| %>
    <div class="form-group mb-2">
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>
    <div class="form-group mb-2">
      <%= form.label :text %><br>
      <%= form.text_area :text, class: "form-control", rows: "3", required: true  %>
    </div>
    <div>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :title, style: "display: block" %>
          <%= form.text_field :title, class: 'form-control', placeholder: "Enter title", required: true %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :author, style: "display: block" %>
          <%= form.text_field :author, class: 'form-control', placeholder: "Enter author", required: true %>
        </div>
      </div>
    </div>

    <div class="row mt-3 mb-3">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :creation_date, style: "display: block" %>
          <%= form.date_field :creation_date, class: 'form-control', min: Date.today %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :published_date, style: "display: block" %>
          <%= form.date_field :published_date, class: 'form-control', min: Date.today %>
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :status, style: "display: block" %>
          <%= form.select :status, Post.statuses.keys, class: 'form-select form-select-lg mb-3' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :image, style: "display: block" %>
        <%= form.file_field :image, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :video, style: "display: block" %>
        <%= form.file_field :video, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group mb-3 mt-3">
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content, class: 'form-control', placeholder: "Write something about post.", rows: "5", required: true %>
  </div>

  <div class="col-md-12 mt-3">
    <div class="row">
      <div class="col-md-10">
        <%= form.submit class: "btn btn-primary" %>
      </div>
      <div class="col-md-2">
        <%= link_to "Back", root_path, class: "btn btn-outline-dark" %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h5 class="card-title">
    <strong>Title: </strong>
    <%= post.title %>
  </h5>
  <hr>
  <p>
    <strong>Status:</strong>
    <%= post.status %>
  </p>

  <p>
    <strong>Creation date:</strong>
    <%= post.creation_date.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <strong>Published date:</strong>
    <%= post.published_date.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= post.author %>
  </p>

  <p class="card-text">
    <strong>Content: </strong>
    <%= post.content %>
  </p>
</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-12 mx-auto">
    <div class="card shadow">
      <div class="card-body">
        <h1>Editing post</h1>
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "shared/flash_message", notice: notice %>

<div class="container">
  <div class="row">
    <div class="row">
      <div class="col-lg-12 d-flex justify-content-between">
        <h1 class="text-center">Posts</h1>
        <%= link_to "New post", new_post_path, class: "btn btn-primary align-self-center" %>
      </div>
    </div>
    <hr>
    <% if @posts.present? %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Published Date</th>
            <th scope="col">Content</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td><%= post.published_date.strftime("%d/%m/%Y") %></td>
              <td><%= post.content.truncate(30) %></td>
              <td><%= link_to "Show", post, class: "btn btn-outline-secondary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="row">
        <div class="col-md-8 mx-auto">
          <%= image_tag ("no_data.jpg"), class: "rounded mx-auto d-block" %>
          <%# <h6 class="text-center text-muted">No data available</h6> %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-12 mx-auto">
    <div class="card shadow">
      <div class="card-body">
        <h1 class="text-center">New post</h1>
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'shared/flash_message', notice: notice %>

<div class="row">
  <div class="col-md-12 mx-auto p-3 shadow">
    <div class="card">
      <div class="row">
        <div class="col-md-6">
          <%= image_tag @post.image, class: "card-img w-50 h-50" if @post.image.present? %>
        </div>
        <div class="col-md-6">
          <%= video_tag @post.video, size: "320x240", controls: true if @post.video.present? %>
        </div>
      </div>
      <div class="card-body">
        <%= render @post %>
        <% if @post.user == current_user %>
          <hr>
          <div class="col-md-12 m-3">
            <div class="row">
              <div class="col-md-4">
                <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-primary" %>            
              </div>
              <div class="col-md-4">
                <%= link_to "Back", root_path, class: "btn btn-outline-dark" %>
              </div>
              <div class="col-md-4">
                <%= link_to "Delete", post_path(@post), class: "btn btn-outline-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
              </div>
            </div>
          </div>
        <% end %>  
      </div>
    </div>
  </div>
</div>

<div class="row mt-3 mb-3">
  <div class="col-md-12 shadow p-3">
    <h2>Comments</h2>
    <%= render "comments/comment", post: @post %>
  </div>
</div>

<div class="row mt-3 mb-3">
  <div class="col-md-12 mx-auto p-3 shadow">
    <div class="card p-3">
      <h2>Add a comment:</h2>
      <%= render "comments/form", post: @post %>
    </div>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong><%= notice %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  	<%= link_to "Blog Application", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "Posts", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
          	<%= link_to "Logout", destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% else %>
          	<%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="text-danger" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-primary' %>
<% end %>